name: Build Docker
on:
  workflow_dispatch:
  push:
    branches:
      - master
  repository_dispatch:
    types: [docker]
jobs:
  generate:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Trigger Rdiscvr Docker
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: bimberlabinternal/Rdiscvr
          event-type: docker

      - name: Remove unnecessary files
        run: |
          df . -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df . -h

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/bimberlabinternal/cellmembrane
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
        with:
          # Use the previous version of buildx to force docker to save a V1 image,
          # since Exacloud's outdated docker version cannot handle V2/OCI:
          version: v0.9.1
          driver-opts: |
            image=moby/buildkit:v0.12.0

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "GH_PAT=${{ secrets.PAT }}"
          pull: true
          push: ${{github.ref == 'refs/heads/master'}}
          tags: ghcr.io/bimberlabinternal/cellmembrane:nightly,ghcr.io/bimberlabinternal/cellmembrane:latest
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.title=cellmembrane
            org.opencontainers.image.description=CellMembrane is an R package with wrappers and pipelines for single cell RNA-seq analysis, developed and maintained by the Bimber Lab.


